# ----------------------------------------------------- 
# Environment Variables
# name: "Default"
# ----------------------------------------------------- 

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

env = GDK_SCALE,1.25


